version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ralphkit
    main: ./main.go
    binary: ralphkit
    ldflags:
      - -s -w
      - -X github.com/kfroemming/ralphkit/cmd.Version={{.Version}}
      - -X github.com/kfroemming/ralphkit/cmd.Commit={{.ShortCommit}}
      - -X github.com/kfroemming/ralphkit/cmd.Date={{.Date}}
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude: ['^docs:', '^test:', '^chore:']

brews:
  - name: ralphkit
    repository:
      owner: kfroemming
      name: homebrew-tap
      token: '{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}'
    directory: Formula
    homepage: https://github.com/kfroemming/ralphkit
    description: Orchestrate Ralph-style autonomous AI coding loops with Claude Code
    license: MIT
    install: |
      bin.install "ralphkit"
    test: |
      system "#{bin}/ralphkit", "--version"
